### ISSUE TITLE
TypeError: undefined is not an object (evaluating '__gCrWeb.autofill.extractForms')

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/InstantLogoSearch#212]
View details in Rollbar: [https://rollbar.com/instantlogosearch/instantlogosearch/items/175/](https://rollbar.com/instantlogosearch/instantlogosearch/items/175/)

```

TypeError: undefined is not an object (evaluating '__gCrWeb.autofill.extractForms')
  File "http://instantlogosearch.com/", line 1, in global code
```

**Comment by staabm** [comment]
any hint on how this issue was resolved?

**Comment by cyberhck** [comment]
@staabm after googling I reached here, it's not resolved, it's a chromium implementation issue which happens if user has autofill enabled (only on iOS though)
